name: map
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: 
  google_maps_webservice : 
  widget_to_marker: ^1.0.6
  custom_map_markers: ^0.0.2+1
  # Added For Clustering example
  flutter_map_marker_cluster: 
  # Added For Clustering example
  flutter_map: 
  # Added For Clustering example
  latlong2: 
  flutter_map_math: ^0.1.6
  # Added for calculating distance from latlong
  geolocator : 
  # Added for getting address from latlong
  geocoding: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/map_theme/
    - assets/images/
  
    
    
module:

  androidX: true # Add this line.
    
  